#!/usr/bin/env bash
# make_membrane.sh — mint a phase-unbraid membrane: value baked in, no input.
#
# Usage: ./make_membrane.sh <N> [a_base] [max_shots]
#   N        the value to be factored — mounted at compile time
#   a_base   coprime base for the phase register (default 2)
#   max_shots  bounded re-measurement budget (default 12)
#
# Pipeline: validate -> generate examples/membrane_<N>.rs (N baked in)
#           -> cargo build --release --example membrane_<N>
#           -> run the artifact -> exit with the membrane's own verdict.
# μ∘δ=id is enforced inside the generated membrane; exit 0 means closed.
set -euo pipefail
cd "$(dirname "$0")"

N="${1:?usage: make_membrane.sh <N> [a_base] [max_shots]}"
A="${2:-2}"
SHOTS="${3:-12}"
NAME="membrane_${N}"

if ! [[ "$N" =~ ^[0-9]+$ ]] || (( N < 4 )); then
  echo "make_membrane: N must be an integer >= 4" >&2; exit 10
fi
if (( N % 2 == 0 )); then
  echo "make_membrane: N=$N is even; the phase register winds odd N (peel 2s first)" >&2; exit 11
fi

cat > "examples/${NAME}.rs" <<RSEOF
//! GENERATED by make_membrane.sh — do not edit by hand.
//! Membrane: the value to be factored is BAKED IN (N = ${N}).
//! No factor-seeking input exists; the run is the witness.
//! Pipeline: comb -> exact QFT -> ONE Born shot -> winding k/M -> CF -> gcd.
//! Exit 0 iff the emitted pair re-multiplies to N via the word ops
//! and passes syzygy [encode; Γ; Λ; μ] — μ∘δ=id as the exit condition.

use g_momonados::native_numeral::{self, encode, multiply_via_word, syzygy_preserves};
use g_momonados::phase_unbraid::run_phase_unbraid;
use num_bigint::BigUint;

const N_VALUE: u64 = ${N};
const A_BASE: u64 = ${A};
const MAX_SHOTS: u32 = ${SHOTS};

fn main() {
    let n = N_VALUE;
    println!("membrane mount: N = {}  word: {}", n, encode(&n.to_string()));
    let res = run_phase_unbraid(n, A_BASE, MAX_SHOTS)
        .unwrap_or_else(|e| { eprintln!("membrane rupture: {}", e); std::process::exit(1); });
    print!("{}", res.trace);
    let (p, q) = match res.factors {
        Some(pair) => pair,
        None => {
            eprintln!("membrane did not close in {} shot(s) — reported as measured, no guess emitted", res.total_shots);
            std::process::exit(2);
        }
    };
    let nb = BigUint::from(n);
    let pb = BigUint::from(p);
    let qb = BigUint::from(q);
    let mult_ok = multiply_via_word(&pb, &qb) == nb;
    let syz_ok = syzygy_preserves(&nb, &pb, &qb);
    if !mult_ok || !syz_ok {
        eprintln!("FROBENIUS FAILURE: p={} q={} mult_ok={} syzygy_ok={} — membrane emitted nothing", p, q, mult_ok, syz_ok);
        std::process::exit(3);
    }
    println!("FACTORS: p = {}   q = {}", p, q);
    println!("p × q = N: {}  [multiply_via_word]", mult_ok);
    println!("syzygy preserves [encode; Γ; Λ; μ]: {}", syz_ok);
    println!("{}", native_numeral::factor_words_line(&pb, &qb));
    println!("μ∘δ = id — membrane closed.");
}
RSEOF

echo "make_membrane: generated examples/${NAME}.rs (N=${N}, a=${A}, shots=${SHOTS})"
cargo build --release --example "${NAME}" 2>&1 | grep -E "^error|Finished" || true
if [[ ! -x "target/release/examples/${NAME}" ]]; then
  echo "make_membrane: build failed" >&2; exit 12
fi
echo "make_membrane: running target/release/examples/${NAME}"
"target/release/examples/${NAME}"
