//! GENERATED by make_membrane.sh — do not edit by hand.
//! Membrane: the value to be factored is BAKED IN (N = 16744463).
//! No factor-seeking input exists; the run is the witness.
//! Pipeline: comb -> exact QFT -> ONE Born shot -> winding k/M -> CF -> gcd.
//! Exit 0 iff the emitted pair re-multiplies to N via the word ops
//! and passes syzygy [encode; Γ; Λ; μ] — μ∘δ=id as the exit condition.

use g_momonados::native_numeral::{self, encode, multiply_via_word, syzygy_preserves};
use g_momonados::phase_unbraid::run_phase_unbraid;
use num_bigint::BigUint;

const N_VALUE: u64 = 16744463;
const A_BASE: u64 = 2;
const MAX_SHOTS: u32 = 24;

fn main() {
    let n = N_VALUE;
    println!("membrane mount: N = {}  word: {}", n, encode(&n.to_string()));
    let res = run_phase_unbraid(n, A_BASE, MAX_SHOTS)
        .unwrap_or_else(|e| { eprintln!("membrane rupture: {}", e); std::process::exit(1); });
    print!("{}", res.trace);
    let (p, q) = match res.factors {
        Some(pair) => pair,
        None => {
            eprintln!("membrane did not close in {} shot(s) — reported as measured, no guess emitted", res.total_shots);
            std::process::exit(2);
        }
    };
    let nb = BigUint::from(n);
    let pb = BigUint::from(p);
    let qb = BigUint::from(q);
    let mult_ok = multiply_via_word(&pb, &qb) == nb;
    let syz_ok = syzygy_preserves(&nb, &pb, &qb);
    if !mult_ok || !syz_ok {
        eprintln!("FROBENIUS FAILURE: p={} q={} mult_ok={} syzygy_ok={} — membrane emitted nothing", p, q, mult_ok, syz_ok);
        std::process::exit(3);
    }
    println!("FACTORS: p = {}   q = {}", p, q);
    println!("p × q = N: {}  [multiply_via_word]", mult_ok);
    println!("syzygy preserves [encode; Γ; Λ; μ]: {}", syz_ok);
    println!("{}", native_numeral::factor_words_line(&pb, &qb));
    println!("μ∘δ = id — membrane closed.");
}
